name: Deploy Terraform

on:
  push:
    branches:
      - feature/**
    paths:
      - 'terraform/dev-env**'
  pull_request:
    types: [closed]  # triggers only when PR is merged
    branches:
      - dev
    paths:
      - 'terraform/dev-env/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    environment: dev  # this enforces manual approval before apply

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      - name: Fetch AWS Account ID
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          echo "TF_VAR_AWS_ACCT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV
          echo "TF_VAR_AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV

      - name: Set up Git credentials for private modules
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Terraform Init
        working-directory: ./terraform/dev-env
        run: |
          terraform init \
            -backend-config="bucket=${AWS_ACCOUNT_ID}-dev-app-state-bucket" \
            -backend-config="key=${{ github.ref_name }}.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="use_lockfile=true"

      - name: Terraform Validate
        working-directory: ./terraform/dev-env
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform/dev-env
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'pull_request' && github.event.pull_request.merged == true
        working-directory: ./terraform/dev-env
        run: terraform apply -auto-approve
