name: Deploy Terraform

on:
  push:
    branches:
      - feature/**
    paths:
      - 'terraform/dev-env/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'terraform/dev-env/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write  # needed to post PR comments

jobs:
  terraform-deploy:
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: "${{ github.actor }}-${{ github.run_id }}"

      - name: Fetch AWS Account ID
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          echo "TF_VAR_acct_id=$AWS_ACCOUNT_ID" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"  # Debugging step

      - name: Set up Git credentials for private modules
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Terraform Init
        working-directory: ./terraform/dev-env
        run: |
          terraform init \
            -backend-config="bucket=${AWS_ACCOUNT_ID}-dev-app-state-bucket" \
            -backend-config="key=${GITHUB_REF##*/}.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="use_lockfile=true"

      - name: Terraform Validate
        working-directory: ./terraform/dev-env
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform/dev-env
        run: terraform plan -input=false -no-color | tee tfplan.txt

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./terraform/root-module/tfplan.txt
